language: python
sudo: false
jobs:
  include:
    - python: "3.6"
    - python: "3.7"
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - flake8 submit_cgap
  - coverage run --source=submit_cgap -m pytest -vv
  - if [ "$TRAVIS_PYTHON_VERSION" == "3.6" ]; then coveralls; fi;
deploy:
  provider: script
  script: if [ "$TRAVIS_PYTHON_VERSION" == "3.6" ]; then make publish fi
  on:
    tags: true
after_success:
  - echo "Finished running tests"
  - echo "A github webhook is supposed to cause readthedocs to update when master changes, so no action needed here."
