[tool.poetry]
name = "SubmitCGAP"
version = "0.1.0"
description = "Support for uploading file submissions to the Clinical Genomics Analysis Platform (CGAP)."
authors = ["4DN-DCIC Team <support@4dnucleome.org>"]
license = "MIT"
readme = "README.rst"
keywords = ["submit-cgap"]
homepage = "https://github.com/dbmi-bgm/SubmitCGAP"
repository = "https://github.com/dbmi-bgm/SubmitCGAP.git"
packages = [
  { include="submit_cgap", from="." }
]

classifiers = [
  'Development Status :: 4 - Beta',
  'Intended Audience :: Developers',
  'License :: OSI Approved :: MIT License',
  'Natural Language :: English',
  'Programming Language :: Python :: 3.6',
]
include = [
  "LICENSE",
]

[tool.poetry.dependencies]
python = ">=3.6,<3.7"
boto3 = ">=1.10.50,<2"

[tool.poetry.dev-dependencies]
nose = ">=1.3.7"
pygments = ">=2"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
